# Generated by Django 2.2.2 on 2019-06-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('exchange', models.CharField(max_length=100, null=True)),
                ('symbol', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('change_amount', models.FloatField(null=True)),
                ('percent_change', models.FloatField(null=True)),
                ('change_class', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='headline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='promo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
